// react-test/src/components/TodoList.jsx
import React, { useState, useEffect } from "react";
import { TodoCard } from "./TodoCard";
import { TodoForm } from "./TodoForm";
import { getTodos, createTodo, updateTodo, deleteTodo } from "../services/api";

export const TodoList = () => {
    const [todos, setTodos] = useState([])
    const [editingTodo, setEditingTodo] = useState(null)

    useEffect(() => {
        fetchTodos()
    }, [])

    const fetchTodos = async () => {
        try {
            const response = await getTodos()
            setTodos(response.data)
        } catch (error) {
            console.error('Error fetching todos:', error)
        }
    }

    const handleCreate = async (newTodo) => {
        try {
            await createTodo(newTodo)
            fetchTodos()
        } catch (error) {
            console.error('Error creating new todo:', error)
        }
    }

    const handleUpdate = async (updatedTodo) => {
        try {
            const response = await updateTodo(updatedTodo.id, updatedTodo)
            setEditingTodo(null)
            fetchTodos(prevTodo => prevTodo.map(todo =>
                todo.id === response.data.id ? response.data : todo
            ))
        } catch (error) {
            console.error('Error updating todo:', error)
        }
    }

    const handleDelete = async (id) => {
        try {
            await deleteTodo(id)
            setTodos(prevTodo => prevTodo.filter(todo => todo.id !== id))
        } catch (error) {
            console.error('Error deleting todo:', error)
        }
    }
    return (
        <div className="todo-list">
            <TodoForm onSubmit={editingTodo ? handleUpdate : handleCreate} initialData={editingTodo} />
            <hr />
            <div className="todo-cards">
                {todos.map(todo => (
                    <TodoCard
                        key={todo.id}
                        todo={todo}
                        onDelete={handleDelete}
                        onUpdate={() => setEditingTodo(todo)}
                    />
                ))}
            </div>
        </div>
    )
}

// vue-task/src/components/TodoList.vue
<template>
    <div class="todo-list">
        <h2>Todo list</h2>
        <TodoForm :initialTodo="editingTodo" @submit="handleSubmit" />
        <div v-if="loading">Loading...</div>
        <div v-else-if="error">Error: {{ error }}</div>
        <div v-else class="todo-cards">
            <TodoCard v-for="todo in todos" :key="todo.id" :todo="todo" @update="startEditing" @delete="handleDelete" />
        </div>
    </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { api } from '../service/api';
import TodoForm from './TodoForm.vue';
import TodoCard from './TodoCard.vue';

const todos = ref([]);
const editingTodo = ref(null);
const loading = ref(true);
const error = ref(null);

const fetchTodos = async () => {
    loading.value = true;
    error.value = null;
    try {
        const response = await api.getTodos();
        if (response.data && Array.isArray(response.data.data)) {
            todos.value = response.data.data;
        } else {
            throw new Error('Unexpected response format');
        }
    } catch (err) {
        console.error('Error fetching todos:', err);
        error.value = 'Failed to fetch todos. Please try again.';
    } finally {
        loading.value = false;
    }
};

const handleSubmit = async (todo) => {
    try {
        let response
        if (todo.id) {
            response = await api.updateTodo(todo.id, todo);
        } else {
            response = await api.createTodo(todo);
        }
        editingTodo.value = null;
        fetchTodos();
    } catch (err) {
        console.error('Error saving todo:', err);
        if (err.response) {
            console.error('Response data:', err.response.data);
            console.error('Response status:', err.response.status);
            console.error('Response headers:', err.response.headers);
        }
        error.value = 'Failed to save todo. Please try again.';
    }
};

const startEditing = (todo) => {
    editingTodo.value = { ...todo };
};

const handleDelete = async (id) => {
    try {
        await api.deleteTodo(id);
        todos.value = todos.value.filter(todo => todo.id !== id);
    } catch (err) {
        console.error('Error deleting todo:', err);
        error.value = 'Failed to delete todo. Please try again.';
    }
};

onMounted(fetchTodos);
</script>


<style scoped>
.todo-list {
    margin-top: 20px;
}

.todo-cards {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    gap: 20px;
    margin-top: 20px;
}
</style>
