// vue-task/src/components/TodoForm.vue
<template>
    <form @submit.prevent="onSubmit" class="todo-form">
        <input v-model="todoData.title" placeholder="Title..." required>
        <textarea v-model="todoData.description" placeholder="Description..." required></textarea>
        <label>
            Check if the task is completed.
            <input type="checkbox" v-model="todoData.isDone">
        </label>
        <button type="submit">{{ todoData.id ? 'Update' : 'Add' }} Todo</button>
    </form>
    <hr>
</template>

<script setup>
import { ref, watch } from 'vue';

const props = defineProps({
    initialTodo: Object
});

const emit = defineEmits(['submit']);

const todoData = ref({
    id: null,
    title: '',
    description: '',
    isDone: false
});

watch(() => props.initialTodo, (newVal) => {
    if (newVal) {
        todoData.value = {
            id: newVal.id,
            title: newVal.title,
            description: newVal.description,
            isDone: newVal.isDone
        };
    } else {
        todoData.value = { id: null, title: '', description: '', isDone: false };
    }
}, { immediate: true });

const onSubmit = () => {
    const newTodo = {
        id: todoData.value.id,
        title: todoData.value.title,
        description: todoData.value.description,
        isDone: todoData.value.isDone
    };
    emit('submit', newTodo);
};
</script>


<style>
.todo-form {
    display: flex;
    flex-direction: column;
    gap: 10px;
    margin-bottom: 20px;
}

.todo-form input[type="text"],
.todo-form textarea {
    padding: 8px;
    border: 1px solid #ddd;
    border-radius: 4px;
}

.todo-form button {
    padding: 8px;
    background-color: #4CAF50;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

.todo-form button:hover {
    background-color: #45a049;
}
</style>

// react-test/src/components/TodoForm.jsx
import React, { useEffect, useState } from "react";

export const TodoForm = ({ onSubmit, initialData }) => {
    const [todo, setTodo] = useState({
        title: '',
        description: '',
        is_done: false
    })

    useEffect(() => {
        if (initialData) {
            setTodo(initialData)
        }
    }, [initialData])

    const handleChange = (e) => {
        const { name, value, type, checked } = e.target
        setTodo(prevTodo => ({
            ...prevTodo,
            [name]: type === 'checkbox' ? checked : value
        }))
    }

    const handleSubmit = (e) => {
        e.preventDefault()
        onSubmit({
            id: todo.id,
            title: todo.title,
            description: todo.description,
            is_done: todo.is_done,
            date_rreated: todo.date_created
        })
        setTodo({ title: '', description: '', is_done: false })
    }
    return (
        <form className="todo-form" onSubmit={handleSubmit}>
            <input
                type="text"
                name="title"
                value={todo.title}
                onChange={handleChange}
                placeholder="Todo title"
                required
            />
            <textarea
                name="description"
                value={todo.description}
                onChange={handleChange}
                placeholder="Todo description"
                required
            />
            <label>
                Check if done.
                <input
                    type="checkbox"
                    name="is_done"
                    checked={todo.is_done}
                    onChange={handleChange}
                />
            </label>
            <button type="submit">
                {initialData ? 'Update' : 'Add'}
            </button>
        </form>
    )
}
